### ISSUE TITLE
minor - print target on cf undeploy

### ISSUE THREAD

**Issue by andre68723** [cloudfoundry/multiapps-cli-plugin#143]
### Description
Hi,

minor but long time wish, could you add the target org/space on the confirmation prompt?

```
cf undeploy <foo> --delete-services

Really undeploy multi-target app <foo> ? (y/n)> 
```

As this is a irrevocable action and often using bash in parallel session, I'd usually cancel and verify once again
with cf target that I'm currently in the correct space

### Expected Result
```
cf undeploy <foo> --delete-services

Really undeploy multi-target app <foo> in org <org> / space <space> ? (y/n)> 
```

Thanks!
Andre

**Comment by IvanBorislavovDimitrov** [comment]
Hi Andre,

Thank you for the proposal. I've opened an internal item in order to add the org and space during undeploy: https://sapjira.wdf.sap.corp/browse/LMCROSSITXSADEPLOY-2457

Best regards,
Ivan

**Comment by IvanBorislavovDimitrov** [comment]
Will be fixed with next release
