### ISSUE TITLE
Update just the resources with --all-resources

### ISSUE THREAD

**Issue by iggycoder** [cloudfoundry/multiapps-cli-plugin#151]
### Description
With an older version of the multiapps plugin it was possible to just update resources inside an mta when doing the following:
```shell
mbt mtad-gen -t ./mta
cd mta; cf deploy --all-resources
```

With the newer version `2.6.3` cf deploy complains about the paths generated inside the `mtad.yaml` under modules. But with the option `--all-resources`, `cf deploy` should not validate the `modules` section at all.

It would be beneficial to have a chance to have the partial deployment feature available again to just update the resources and their configs without uploading and redeploying modules as well.

Error Output: 
```shell
Error retrieving MTA: Error building MTA Archive: file path /Users/xxx/yyyy/Sources/zzz/mta/<module-path> not found
```

### Your environment
*	MultiApps CF CLI Plugin version - 2.6.3
*	which CF vendor is used - SAP BTP CF Environment

**Comment by radito3** [comment]
Hello,
The `--all-resources` option does not exclude the modules of the MTA.
What is the path error that the plugin displays?

**Comment by iggycoder** [comment]
Ok, understood - the error output I got (listed in the issue I filed) is mentioning that it cannot find the path of the first listed module - which makes sense since I am just generating an `mtad.yaml` without any build artifacts.

What would be a viable option to update all resources, excluding the modules? What is the exact use case for the option `--all-resources` in the current form?

**Comment by radito3** [comment]
Hello,
There is currently no option to "exclude" modules/resources from deployment.
My recommendation is to use selective deploy to specify only one module or make a mock module so that it can be used for that purpose.

**Comment by iggycoder** [comment]
Ok. Thanks for the clarification. I think it might be a valid use case for multiapps to just update all resources :)
