### ISSUE TITLE
Recent release not available through cf-community

### ISSUE THREAD

**Issue by rlindner81** [cloudfoundry/multiapps-cli-plugin#156]
### Description
I see the latest release here is 3.0.1 (Sep 30, 2022).
When I look for `multiapps` through cf-cli I can only find 2.7.0 (Nov 23, 2021).

```
d057156@M12VHYH70W ~ % cf repo-plugins | grep multiapps
multiapps                       2.7.0     MultiApps cli plugin performing multitarget application(MTA) operations in Cloud Foundry, such as deploying, removing, viewing etc.
```

Why have the releases not been published to cf-community for almost a year?

### Your environment
* Mac OS
* CF-CLI version - 8.5.0
* MultiApps CF CLI Plugin version - 2.7.0.
* which CF vendor is used - SAP BTP

**Comment by boyan-velinov** [comment]
@rlindner81  You are correct. The latest release is 3.0.1 and it is the recommended one.

We have changed the CF CLI Plugin repo to refer the 3.0.1 but somehow it still does not appear:
https://github.com/cloudfoundry/cli-plugin-repo/commit/9acee116ad2520c00670ad424b50494f9be9298c
https://github.com/cloudfoundry/cli-plugin-repo/commit/76bb826802751e707e833ff4b451f7d1b122e7a2

We are investigating the problem on the CF-Community reop. But if you have technical possiblity, we encourage the usage of 3.0.1

**Comment by rlindner81** [comment]
Very weird... I'll see if I can set it up so the latest binary is downloaded directly from Github.

**Comment by rlindner81** [comment]
Works fine now
