### ISSUE TITLE
linux-arm64 support for multiapps plugin

### ISSUE THREAD

**Issue by dus2001** [cloudfoundry/multiapps-cli-plugin#166]
Hello,

My team is working with CAP/CDS/MTA apps in an Ubuntu environment. Our development environment Mac Arm (M2). But to freeze on our component versions we are using a Ubuntu VM on Mac Arm 64. Thus we are using linux with Arm64.

This way we are able to maintain multiple VM instances for different state of applications. 2 of our applications are stuck with a prior version of CDS (5.x). Yes we understand we have to update those, but until then we have to support them.

So having this VM helps us maintain the state of VM Node/CDS/Component versions same as what is deployed in production landscape.

Now a simple challenge, we are unable to deploy the MTAR files from the same ubuntu. We are exporting the mtar's to host and deploying using CF there. And reason is CF CLI plugin for multiapps is not available for linux-arm64. Would it be possible to make that available, it will just make our life a little bit easier. Or how can we build it ?

Thank you

**Comment by mattreddy3** [comment]
Maybe it would be better to change the subject to "linux-arm64 support for multiapps plugin"? I had to search the issues for keyword "arm" to identify this issue.

**Comment by dus2001** [comment]
> Maybe it would be better to change the subject to "linux-arm64 support for multiapps plugin"? I had to search the issues for keyword "arm" to identify this issue.

changed

**Comment by theghost5800** [comment]
Hello,

Our cf cli plugin have hard dependency to cf cli in order to work. As I can see there is already [builds](https://github.com/cloudfoundry/cli/releases/tag/v8.7.3) of cf cli for linux and mac arm64 but [cf cli repo plugins](https://github.com/cloudfoundry/cli-plugin-repo/issues/448) still doesn't support distribution of macos/arm64 and linux/arm64 binaries. 

We will plan to add in future releases binaries for these platforms. 

At least for now you can try to clone this repository, edit `build.sh` script for relevant os and platform(you can use this [change](https://github.com/theghost5800/multiapps-cli-plugin/commit/5f1d3e674ec8b3fe4c69c88ea6220dd522c26862) as reference) and execute the script. After build of binary you can install the plugin by `cf install-plugin <path_to_binary>` and then you can use it on arm64 systems.

**Comment by dus2001** [comment]
> Hello,
> 
> Our cf cli plugin have hard dependency to cf cli in order to work. As I can see there is already [builds](https://github.com/cloudfoundry/cli/releases/tag/v8.7.3) of cf cli for linux and mac arm64 but [cf cli repo plugins](https://github.com/cloudfoundry/cli-plugin-repo/issues/448) still doesn't support distribution of macos/arm64 and linux/arm64 binaries.
> 
> We will plan to add in future releases binaries for these platforms.
> 
> At least for now you can try to clone this repository, edit `build.sh` script for relevant os and platform(you can use this [change](https://github.com/theghost5800/multiapps-cli-plugin/commit/5f1d3e674ec8b3fe4c69c88ea6220dd522c26862) as reference) and execute the script. After build of binary you can install the plugin by `cf install-plugin <path_to_binary>` and then you can use it on arm64 systems.

Thank you @theghost5800 We will attempt this.

**Comment by dus2001** [comment]
may be I am not supposed to leave the issue itself open until the build is automatically available. new to github issues. not sure of protocols

**Comment by theghost5800** [comment]
Hello, I am glad to share with you that we have made available binaries for MacOS and Linux arm architecture. You can find them in the latest release [3.1.1](https://github.com/cloudfoundry/multiapps-cli-plugin/releases/tag/v3.1.1)
[multiapps-plugin.linuxarm64](https://github.com/cloudfoundry/multiapps-cli-plugin/releases/download/v3.1.1/multiapps-plugin.linuxarm64)
[multiapps-plugin.osxarm64](https://github.com/cloudfoundry/multiapps-cli-plugin/releases/download/v3.1.1/multiapps-plugin.osxarm64)

**Comment by mattreddy3** [comment]
Thanks for your support! Will help my dev team

**Comment by dus2001** [comment]
Thank you. appreciate your support. This will definitely help us.
