### ISSUE TITLE
Run automated smoke tests before switching the routes during a mta blue green deployment

### ISSUE THREAD

**Issue by fwilhe** [cloudfoundry/multiapps-cli-plugin#65]
### Description

Context: I'm working on [s4sdk pipeline](https://github.com/sap/cloud-s4-sdk-pipeline), which can build mta projects and deploy them to SAP Cloud Platform using this plugin and the cf cli.

We would like to run automated smoke tests as part of the blue-green deployment before the routes are switched. The goal is to avoid the need of manual tests. If the new version of the app is broken (as in, does not even pass smoke tests), the old version should stay up. In the best case, this could be fully automated. For example, after deploying the new version of the application, a test script should run (in the most simple case this would just check if some api endpoint is up), and if this script succeeds the deployment should continue as usual. If the script fails, in the best case the old deployment should stay up automatically and the cf cli should return with a non-zero exit code to indicate the issue.

This request originates in a request by one of our consumers of [s4sdk pipeline](https://github.com/sap/cloud-s4-sdk-pipeline).

Is there a way to do this as of now? If not, can it be implemented?

### Your environment
*	MultiApps CF CLI Plugin version - 2.0.7
*	which CF vendor is used - SAP

### Steps to reproduce

Does not apply

### Additional information

We use [`cloudFoundryDeploy` step, method `deployMta` in piper-lib-os](https://github.com/SAP/jenkins-library/blob/78400cad9bdce2b1b638726eee16ee9e03202c9f/vars/cloudFoundryDeploy.groovy#L213) with flags `-f --no-confirm`.

**Comment by ddonchev** [comment]
Hi Florian and thank you for your input!

If running such integration tests may be done from within a cf app container, there may a good candidate for a solution.
Recently the "hooks" functionality was released. It can be utilised to schedule cf tasks on applications in different moments of their lifecycle.
Feature documentation: https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/projects/1#card-31735502 

With MTA modelling one can have a dedicated module to be deployed last as a cf app, which may not even be started. This module would receive the proper idle urls of the idle apps. Using the hooks functionality a task can be executed in that app's container to do the test. 

The currently supported events(phases) are before and after live or idle applications get stopped, or when live apps loose their routes. None of them fit well this scenario, so a new phase can be introduced - e.g. before an idle application is started.

Do you think this solution may work for your case?

**Comment by fwilhe** [comment]
Not relevant anymore
